# Generated by Django 3.2.9 on 2022-03-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_auto_20220315_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participant',
        ),
        migrations.AddField(
            model_name='member',
            name='event',
            field=models.ManyToManyField(to='Accounting.event'),
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('purpose', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.event')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.member')),
            ],
        ),
    ]
