# Generated by Django 3.2.9 on 2022-03-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0003_auto_20220315_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='payee',
            field=models.ManyToManyField(related_name='payee', to='Accounting.member'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='Accounting.member'),
        ),
    ]
