# Generated by Django 3.2.9 on 2022-03-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0004_auto_20220315_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
