# Generated by Django 3.2.9 on 2022-03-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0005_alter_pay_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='Member',
            field=models.ManyToManyField(to='Accounting.member'),
        ),
    ]
