# Generated by Django 3.2.9 on 2022-03-16 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0006_auto_20220316_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
