# Generated by Django 3.2.9 on 2022-04-04 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounting', '0008_auto_20220405_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Member',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
