# Generated by Django 3.2.9 on 2022-04-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0009_alter_event_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
