# Generated by Django 3.2.9 on 2022-04-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0011_alter_event_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
