# Generated by Django 3.2.9 on 2022-04-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0014_auto_20220406_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creater',
        ),
    ]
