# Generated by Django 3.2.9 on 2022-04-06 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounting', '0015_remove_event_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
    ]
