# Generated by Django 3.2.9 on 2022-04-06 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounting', '0017_alter_event_creater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creater',
        ),
        migrations.AddField(
            model_name='event',
            name='creater',
            field=models.ManyToManyField(blank=True, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
    ]
