# Generated by Django 3.2.9 on 2022-04-06 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounting', '0018_auto_20220407_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creater',
        ),
        migrations.AddField(
            model_name='event',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
    ]
